"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import dotenv_values
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The SECRET_KEY is used for signing cookies, CSRF tokens, sessions, etc.
# It should NEVER be public. Here we load it either from GitHub Actions env vars or from .env (local).
if os.environ.get('GITHUB_ACTIONS') == 'true':
    # Running in GitHub Actions, get secret from environment variable
    SECRET_KEY = os.environ.get('SECRET_KEY')
else:
    # Load environment variables from the .env file located in the project root.
    # This allows you to keep secret keys and sensitive info out of your code.
    env_path = BASE_DIR / '.env'
    if Path(env_path).exists():
        env = dotenv_values(env_path)
    else:
        raise FileNotFoundError("Warning: .env file not found. Please create one in the project root.")
    # Running locally, get secret from .env file
    SECRET_KEY = env.get('SECRET_KEY')

# Raise an error if SECRET_KEY is not found
# This ensures your app never runs without a key (which would be unsafe).
if not SECRET_KEY:
    raise ValueError("SECRET_KEY not found in environment or .env file")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True is used during development to display detailed error pages.
# In production, DEBUG must always be False to hide sensitive information.
DEBUG = False

# ALLOWED_HOSTS defines which domains/hosts are allowed to serve this app.
# When in production, this should include your real domain (e.g. 'myapp.com').
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                  # CORS support (ensures communication between frontend and backend)
    'shortener',                    # URL shortener app
]

# MIDDLEWARE is a list of security and request-processing layers.
# Each one intercepts requests/responses and adds protection or features.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',    # here is applied CORS from INSTALLED_APPS, as a security measure
]

# CORS_ALLOWED_ORIGINS defines which frontend origins are allowed to access this backend via cross-origin requests.
# This is needed when your frontend (e.g., React at localhost:3000) talks to your Django API during development.
# Will be modified in production to real frontend domain.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# ROOT_URLCONF tells Django where to find the main URL routing configuration.
# This file maps URLs (like /admin or /test-error) to Python view functions.
ROOT_URLCONF = 'backend.urls'

# TEMPLATES defines how Django handles HTML rendering.
# It specifies where templates are stored and what context data is available globally.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION defines the entry point for WSGI-compatible web servers.
# WSGI = Web Server Gateway Interface (used by servers like Gunicorn, Apache, etc.).
# Django automatically uses this file when running in a synchronous (classic) environment.
WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES defines which database engine Django should use and where it is located.
# By default, Django uses SQLite (a simple file-based database) — perfect for local development.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# These validators apply ONLY to user passwords (e.g., admin or registered users).
# They do NOT affect system secrets (SECRET_KEY, DB passwords, etc.).
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL defines the base URL path for serving static assets (like CSS, JS, and images).
# During development, Django serves them automatically via runserver.
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD defines what type of 'id' field is automatically created for models.
# BigAutoField = a large integer field that auto-increments with each new record (default since Django 4+).
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
